services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5674:5672"
      - "15674:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - "8000:80"
    volumes:
      - ./src/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password

volumes:
  mysql_data:
  rabbitmq_data:
